name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          cd final_task/src
          python3 -m venv .venv
          . .venv/bin/activate
          pip install -r requirements.txt

      - name: Train model
        run: |
          cd final_task/src
          . .venv/bin/activate
          python train_model.py

      - name: Upload model
        uses: actions/upload-artifact@v2
        with:
          name: model
          path: final_task/src/model.pkl

  build:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download model
        uses: actions/download-artifact@v2
        with:
          name: model
          path: final_task/src/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: final_task/
          file: final_task/Dockerfile
          push: true
          tags: yourusername/your-repository:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy application
        run: echo "Deploying the application..."
